// Generated by https://quicktype.io

export interface Filmes {
    page:          number;
    results:       Result[];
    total_pages:   number;
    total_results: number;
}

export interface Result {
    name?:             string;
    original_name?:    string;
    origin_country?:   string[];
    vote_count:        number;
    backdrop_path:     string;
    vote_average:      number;
    genre_ids:         number[];
    id:                number;
    original_language: OriginalLanguage;
    overview:          string;
    poster_path:       string;
    first_air_date?:   string;
    popularity:        number;
    media_type:        MediaType;
    video?:            boolean;
    release_date?:     string;
    adult?:            boolean;
    title?:            string;
    original_title?:   string;
}

export enum MediaType {
    Movie = "movie",
    Tv = "tv",
}

export enum OriginalLanguage {
    En = "en",
    Es = "es",
    Fr = "fr",
    Ko = "ko",
}
